# Generated by Django 4.2.6 on 2023-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
