# Generated by Django 4.2.6 on 2023-10-18 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_date_modified_remove_task_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title_post',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
